spring.datasource.url=jdbc:mysql://192.168.11.2:33060/spring-boot-hibernate?useSSL=false
#spring.datasource.url=jdbc:mysql://192.168.10.12:33060/HIBERNATE?useSSL=false
spring.datasource.username=user
spring.datasource.password=resu

## Hibernate Properties
#Hibernate ddl auto (create, create-drop, update)
#Исользуются для автоматического создания/обновления таблицы в бд, используя нашу сущность
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=7171