DROP TABLE IF EXISTS Wallets;

CREATE TABLE Wallets (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
cash VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS Products;

CREATE TABLE Products (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
quantity INT NOT NULL,
price DOUBLE NOT NULL
);